let mongoose = require('mongoose');

module.exports = mongoose.model('level',{
    name:{
        type:String
    },
    mobile:{
        type:Number
    },
    lvlNo:{
        type:Number
    },
    lvl1:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl2:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl3:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl4:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl5:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl6:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl7:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl8:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl9:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl10:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl11:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }],
    lvl12:[{
        name:{
            type:String
        },
        mobile:{
            type:Number
        },
        earning:{
            utility:{
                type:Number,
            },
            utilityToday:{
                type:Number,
            },
            utilityMonth:{
                type:Number,
            },
            eComm:{
                type:Number,
            },
            eCommToday:{
                type:Number,
            },
            eCommMonth:{
                type:Number,
            },
            demat:{
                type:Number,
            },
            ad:{
                type:Number,
            },
            adToday:{
                type:Number,
            },
            adMonth:{
                type:Number,
            }
        }
    }]
})